name: .NET

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test (with coverage)
      run: |
        # Run tests and collect coverage (XPlat Code Coverage)
        dotnet test --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: List coverage files (for debugging)
      run: find ./coverage -name "*.xml" -type f || echo "No coverage files found"

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: './coverage/**/coverage.cobertura.xml'
        if-no-files-found: warn

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: './coverage/**/coverage.cobertura.xml'
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
